rule _IcedID {
   meta:
      description = "IcedID"
      author = "KrknSec"
      date = "2022-04-30"
   strings:
      $s1 = "CzRles" fullword ascii
      $s2 = "!D&[)u" fullword ascii
      $s3 = "%PTjzC/" fullword ascii
      $s4 = "G :/oV" fullword ascii
      $s5 = "J?HqMwR;" fullword ascii
      $s6 = "}+`*xT3\":2s" fullword ascii
      $s7 = "?A?uk\"+D" fullword ascii
      $s8 = "L1O&o&" fullword ascii
      $s9 = "|}.>Ud" fullword ascii
      $s10 = "b!q0^\\" fullword ascii
      $s11 = " To identify genuine Microsoft software, see howtotell.com." fullword ascii
      $s12 = " You may order trial programs, or Oracle may include additional programs with your order which you may use for trial, nonproduct" ascii
      $s13 = "ion purposes only. You may not use the trial programs to provide or attend third party training on the content and/or" fullword ascii
      $s14 = " Does the software collect my personal information? If you connect your computer to the Internet," fullword ascii
      $s15 = " not sold, Microsoft reserves all rights (such as rights under intellectual property laws) not expressly" fullword ascii
      $s16 = " MICROSOFT EXCLUDES ALL IMPLIED WARRA NTIES, INCLUDING THOSE OF" fullword ascii
      $s17 = " we only license it." fullword ascii
      $s18 = " 800-778-7879. In a dispute involving $75,000 or less, Microsoft will promptly reimburse your filing fees" fullword ascii
      $s19 = " ALLOWS. IF YOUR LOCAL LAW REQUIRES A LONGER LIMITED WARRA NTY TERM, DESPITE" fullword ascii
      $s20 = " (unless Microsoft provides other terms with such supplements, updates, or services). You can review this" fullword ascii
      $s21 = " How can I use the software? We do not sell our software or your copy of it " fullword ascii
      $s22 = " Multiple purchase lines may be created on either a requisition or purchase order or may be automatically generated by other" fullword ascii
      $s23 = " 6399. A form is available at go.microsoft.com/fwlink/?linkid=245499. Microsoft will send any" fullword ascii
      $s24 = " any service, data, account or network by any means." fullword ascii
      $s25 = " obtain a license to allow for continued use, or if these alternatives are not commercially reasonable, the Provider may end the" ascii
      $s26 = " obtain a license to allow for continued use, or if these alternatives are not commercially reasonable, the Provider may end the" ascii
      $s27 = " licensed program on a single specified computer." fullword ascii
      $s28 = " license" fullword ascii
      $s29 = " terminated leases and repossessed assets, plus (5) Original cost of assets underlying leases and loans, originated and active o" ascii
      $s30 = " sources must be licensed separately." fullword ascii
      $s31 = " IRE_OLSA_V120103_Def_V122304 Page 3 of 11 " fullword ascii
      $s32 = " disclose, use or permit the disclosure or use by others of the TRMs for any other purpose. You shall not use the TRMs to" fullword ascii
      $s33 = " terminated leases and repossessed assets, plus (5) Original cost of assets underlying leases and loans, originated and active o" ascii
      $s34 = " own most important confidential information or a reasonable degree of care, whichever is greater; (b) to maintain agreements" fullword ascii
      $s35 = "VbxV9dhs" fullword ascii
      $s36 = "l[S?H[" fullword ascii
      $s37 = "P@rw2'" fullword ascii
      $s38 = "iUG^Dn" fullword ascii
      $s39 = ".D 16*" fullword ascii
      $s40 = "d;-gb(" fullword ascii
      $s41 = "JDB+(?" fullword ascii
      $s42 = "/je]IM" fullword ascii
      $s43 = "H{%*RO" fullword ascii
      $s44 = ".M'5Jg" fullword ascii
      $s45 = "T3DYb*" fullword ascii
   condition:
      ( uint16(0) == 0x5a4d and filesize < 200KB and ( 8 of ($s*) )
      ) or ( all of them )
}
